; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:disco_f407vg]
platform = ststm32
board = disco_f407vg
framework = stm32cube
board_build.stm32cube.custom_config_header = yes

monitor_port = COM9       ; The CDC COM port we see
monitor_speed = 115200    ; baud is ignored by USB CDC, but PIO wants a value
monitor_eol = CRLF        ; send \r\n when you press Enter


[platformio]
include_dir = Inc
src_dir = Src
